apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-dockerfile-empty-private-biat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-dockerfile-empty-private-biat
    app.kubernetes.io/part-of: mc-golang-without
  name: devfile-sample-go-basic-dockerfile-empty-private-biat
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: devfile-sample-go-basic-dockerfile-empty-private-biat
status:
  loadBalancer: {}
